#!/usr/bin/env bash

echo "#This file lists all individuals having contributed content to the repository." >> AUTHORS

echo >> AUTHORS

echo "#For how it is generated, see 'generate_authors'." >> AUTHORS

echo >> AUTHORS
echo >> AUTHORS

git log --pretty=format:'%an <%ae>' | sort -u >> AUTHORS
